### ISSUE TITLE
No such module UPnPAtom

### ISSUE THREAD

**Issue by Peterede** [master-nevi/UPnAtom#21]
I am trying to build the example and when I build the Swift example in XCode I get an error that the UPnAtom pod has syntax that is out of date (lines starting with #)

**Comment by master-nevi** [comment]
You should update to Cocoapods 1.0 and run pod install from within the example project.

**Comment by duydatpham** [comment]
Hi friend
I still have this problem when i'm trying to build the "ControlPointDemo_ObjC" example.
I downloaded the lastest in github.
Please help me!
