### ISSUE TITLE
How to act as server and provide content?

### ISSUE THREAD

**Issue by hnaethe** [master-nevi/UPnAtom#23]
Sorry to bug you on this way, but I have no clue how to get in contact with you on another way.
I have put up a question in StackOverflow but I fear you would never see it if I wouldn't tell you.

So please have a look at it and thank you very much for this amazing work!

http://stackoverflow.com/questions/37138178/how-to-act-as-dlna-server-using-upnatom

**Comment by hnaethe** [comment]
Since my question has been closed as too broad I will copy my question here. 

I'm currently using UPnAtom from https://github.com/master-nevi/UPnAtom. I'm a bit unsure if I understand the docs correctly. I want to use this lib to provide content to a TV or other DLNA client. How can I achieve that using this lib?

Or if nobody knows about it, how can I implement it at all? I couldn't find any useful documents explaining how this can be done.

Any help is much appreciated!

**Comment by master-nevi** [comment]
Check out the docs and tools at upnp.org

http://openconnectivity.org/upnp/specifications
